#膜条宽
STRIP_HEIGHT = 18
STRIP_HALF_HEIGHT = STRIP_HEIGHT>>1
STRIP_WIDTH = STRIP_HEIGHT
STRIP_HALF_WIDTH = STRIP_WIDTH>>1

SAMPLING_BORDER=1+STRIP_WIDTH>>3

SAMPLING_MAX_WIDTH = 7
SAMPLING_MIN_WIDTH = SAMPLING_MAX_WIDTH>>1
SAMPLING_WIDTH = 4

SAMPLING_HEIGHT = 5
SAMPLING_MINUS_Y_OFFSET = SAMPLING_HEIGHT>>1
SAMPLING_Y_OFFSET = SAMPLING_HEIGHT - SAMPLING_MINUS_Y_OFFSET
#######

